version: "3.11"
services:
  application:
    build: ./
    restart: always
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - main_network
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    restart: always
    networks:
      - main_network

networks:
  main_network:
    driver: bridge
